### ISSUE TITLE
Feature request: Forgejo support

### ISSUE THREAD

**Issue by deadbaed** [Cyclenerd/hcloud-github-runner#3]
## Is your feature request related to a problem? Please describe.
I am not using GitHub to host my code, but a self hosted instance of [Forgejo](https://forgejo.org), a free (as in freedom) and open source git hosting platform, (like GitHub but self-hostable on your own servers).

Forgejo also has a CI system named Forgejo Actions, and the system resembles a lot to GitHub Actions (see below for differences).

Since Forgejo is self hosted, the only way to run action workflows is to self host your own runners.

It should be possible to re-use logic from this action to spawn a Hetzner server, register a runner with Forgejo, run jobs on it and delete the server afterwards.

## Describe the solution you'd like
It would be nice for this action to have some mechanism/option to install a Forgejo runner on a Forgejo instance instead of GitHub to register a runner to a repository.

## Describe alternatives you've considered
On [Delightful Forgejo](https://codeberg.org/forgejo-contrib/delightful-forgejo) I found [a repository](https://codeberg.org/pierreprinetti/forgejo-hetzner-runner) using Hetzner's API to launch a server and register a runner, like you are doing with this action!

Unfortunately it provides only scripts to create and delete servers, while this action does everything from start to finish!

## Additional context
A project I am working on has a requirement of building software on an aarch64 machine, I want to use Hetzner servers to keep costs low. I hacked the action to make it compatible with Forgejo, see the diff [here](https://github.com/Cyclenerd/hcloud-github-runner/compare/master...deadbaed:hcloud-github-runner:forgejo).

I am interested in letting any Forgejo user create ephemeral servers on Hetzner on their instance by upstreaming my work, while being fully compatibility with the GitHub Actions (since the original use case of this action is to deploy runners for GitHub).

As I said earlier, there are some differences between Forgejo Actions and GitHub actions I had to deal with:

### Register Runner to the Forgejo instance

As of 2025-02-16 and `Forgejo v7.x`, the Forgejo API allows runner creation, but you cannot get the registration token through the API, it can be seen only on the web interface. They have an issue tracking this: https://codeberg.org/forgejo/forgejo/issues/1030.

![Image](https://github.com/user-attachments/assets/b808848f-fc97-486a-881f-67dd66a74f96)

However, the registration token can be reused until it is reset manually.

In my fork, I swapped the `INPUT_GITHUB_TOKEN` secret for a `FORGEJO_RUNNER_REGISTRATION_TOKEN` secret, allowing runner registration on the Forgejo instance.

<img width="1356" alt="Image" src="https://github.com/user-attachments/assets/ea7df579-de10-4ca3-a3cc-0a21d42ffc1f" />

### Install runner on server

Nothing fancy here: download the binary on the server, register it to the Forgejo instance and start it.

### Get runner status

The API does not allow getting status of a runner, which is crucial to know when the runner is ready to accept work.

As a workaround, for each server registration I do the following:
1. Generate a ssh keypair, which is added to Hetzner and used when registering the server (it also disables the email sent by Hetzner which is a bonus, since a ssh key will always be attached to the server).
2. In the `cloud-init` template, I provide a systemd service to start and get status of the Forgejo runner. It enables the possibility to run `ssh root@hetzner-server-ip "systemctl is-active forgejo-runner"` using the ssh key generated before to check if the runner is ready to accept work.
3. Once the runner is registered (or all the retries got used), delete the ssh public key on Hetzner and destroy the local keypair. In my workflow I have 2 ssh keys: one I provide manually and the one automatically generated.

### Run action step on the runner

I did not figure out a way of dynamically dispatching work to the runner (using the `MY_NAME` action variable), so I relied on a static `forgejo-runner-hetzner` label to give work the worker, meaning only one runner can be used a time (I have not tested running two runners at the same time).

Here's the Workflow file I use in my repo:

```yml
name: "Build"
on:
  push:

jobs:
  create-runner:
    name: Create Hetzner Cloud runner
    runs-on: ubuntu-24.04 # `ubuntu-24.04` is the name of my local runner
    outputs:
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
    steps:
      - name: Create runner
        id: create-hcloud-runner
        uses: https://github.com/deadbaed/hcloud-github-runner@forgejo
        with:
          mode: create
          forgejo_runner_registration_token: ${{ secrets.FORGEJO_RUNNER_REGISTRATION_TOKEN }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          server_type: cax11
          image: ubuntu-24.04
          enable_ipv4: false # ipv4 costs more money
          forgejo_use_ssh_for_runner_wait: true
          pre_runner_script: |
            HOME=/root sh <(curl -L https://nixos.org/nix/install) --daemon --yes
            echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf

  do-the-job:
    name: Do the job on the runner
    needs: create-runner # required to start the main job when the runner is ready
    runs-on: forgejo-runner-hetzner  # run the job on the newly created runner
    steps:
      - name: Get code
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Do stuff
        run: |
          uname -a

  export-logs:
    name: Export logs of the runner
    needs: do-the-job # required to wait when the main job is done
    runs-on: forgejo-runner-hetzner
    if: ${{ always() }} # always get the logs, especially if the job failed
    steps:
      - name: Export logs
        run: |
          journalctl -b > /tmp/forgejo-runner-hetzner.log
      - name: Upload sd card image
        uses: https://code.forgejo.org/forgejo/upload-artifact@v3
        with:
          name: forgejo-runner-logs
          path: /tmp/forgejo-runner-hetzner.log

  delete-runner:
    name: Delete Hetzner Cloud runner
    needs:
      - create-runner # required to get output from the create-runner job
      - export-logs # required to wait when the main job and log collection are done
    runs-on: ubuntu-24.04 # `ubuntu-24.04` is the name of my local runner
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Delete runner
        uses: https://github.com/deadbaed/hcloud-github-runner@forgejo
        with:
          mode: delete
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          server_id: ${{ needs.create-runner.outputs.server_id }}

```

### Delete runner

Currently, the only way to delete a runner from Forgejo is to do it via the web interface, resulting in a long list of runners after a while:

<img width="1383" alt="Image" src="https://github.com/user-attachments/assets/eaab04ae-df71-4d20-ad1d-b8fdd35fbfff" />

And you can only delete runners one by one (but that is out of scope for this repository):

![Image](https://github.com/user-attachments/assets/c65d17a6-2bba-4159-9452-7295625c0ce1)

## Limitations

- Only one runner at a time (not tested though)
- Does not use the same actions secrets compared to the GitHub action
- Requires usage of ssh key at Hetzner server creation
- The `MY_FORGEJO_RUNNER_REGISTRATION_TOKEN` input is only required when `MY_MODE` is `create`

## TL;DR

I just gave detailed explanation of what I did in my fork. To upstream my changes to this repo, here's a brief overview of the changes I want to make:

- Add an action input "git_platform" or "forge": the value can be either `github` or `forgejo`
- If `forgejo` forge is used, an ssh key will be created to check status of runner.
- If `forgejo` forge is used, require an additional variable to provide the registration token (which will be ignored if `github` forge is used)
- If `forgejo` forge is used, the `INPUT_GITHUB_TOKEN` will be ignored
- Refactor the `cloud-init` and `create-server` templates to make them Forgejo and GitHub compatible (I do not know how I would do that yet).

I understand the changes can be pretty big, I am opening this issue to know if you would be open to receive those changes in your repo.

Either way, thank you very much for this GitHub action, I had a blast using it for my use case!
